# fly.toml app configuration file generated for hosted-payment-test-aged-glitter-0 on 2024-05-14T18:02:06+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simplify-commerce-hosted-payment'
primary_region = 'syd'

[build]

[env]
  PORT = "8081"
  HOST = "https://(insert-hosted-url-here)"
  SHOPIFY_API_KEY = "insert-shopify-key-here"
  SCOPES = "write_products"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1