# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2f4edaa67ab826c7ab31e5cbbd0cd5d3"
name = "jandklabs"
handle = "jandklabs"
application_url = "https://possibility-cork-connecting-transaction.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jklab-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_customers,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://possibility-cork-connecting-transaction.trycloudflare.com/auth/callback",
  "https://possibility-cork-connecting-transaction.trycloudflare.com/auth/shopify/callback",
  "https://possibility-cork-connecting-transaction.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
